[project]
name = "python-template"
version = "0.1.0"
description = ""
authors = ["Your Naaaaaame <tuffyou@example.commmmmmmmmmm>"]
requires-python = ">=3.11"
dependencies = [
    "discord-py>=2.6.4",
    "python-dotenv>=1.2.1",
]
